<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE model[
<!ELEMENT model (category)+>

<!ELEMENT category (feature)+>
<!ATTLIST category
id CDATA #REQUIRED
name CDATA #REQUIRED
pivot-name NMTOKEN #REQUIRED>

<!ELEMENT feature EMPTY>
<!ATTLIST feature
id CDATA #REQUIRED
name CDATA #REQUIRED
pivot-name CDATA #REQUIRED
position CDATA #REQUIRED>
]>
<model>
<category id="1" name="Mode" pivot-name="mood">
<feature id="1" name="Indicatif" pivot-name="indicative" position="1"/>
<feature id="2" name="Conditionnel" pivot-name="conditional" position="2"/>
<feature id="3" name="Subjonctif" pivot-name="subjunctive" position="3"/>
<feature id="4" name="Impératif" pivot-name="imperative" position="4"/>
<feature id="5" name="Infinitif" pivot-name="infinitive" position="5"/>
<feature id="6" name="Participe" pivot-name="participle" position="6"/>
</category>
<category id="2" name="Temps" pivot-name="tense">
<feature id="7" name="Présent" pivot-name="present" position="0"/>
<feature id="8" name="Imparfait" pivot-name="imperfect" position="0"/>
<feature id="9" name="Futur" pivot-name="future" position="0"/>
<feature id="10" name="Passé simple" pivot-name="simple past" position="0"/>
<feature id="25" name="Passé" pivot-name="past" position="0"/>
</category>
<category id="3" name="Genre" pivot-name="gender">
<feature id="11" name="Masculin" pivot-name="M" position="1"/>
<feature id="12" name="Féminin" pivot-name="F" position="2"/>
</category>
<category id="4" name="Personne" pivot-name="person">
<feature id="13" name="Première personne" pivot-name="1" position="1"/>
<feature id="14" name="Deuxième personne" pivot-name="2" position="2"/>
<feature id="15" name="Troisième personne" pivot-name="3" position="3"/>
</category>
<category id="5" name="Nombre" pivot-name="number">
<feature id="16" name="Singulier" pivot-name="S" position="1"/>
<feature id="17" name="Pluriel" pivot-name="P" position="2"/>
</category>
<category id="6" name="Auxiliaire(s)" pivot-name="auxiliary">
<feature id="18" name="être" pivot-name="" position="1"/>
<feature id="19" name="avoir" pivot-name="" position="2"/>
</category>
<category id="11" name="Variation(s)" pivot-name="variation">
<feature id="1539" name="graphie erronée" pivot-name="" position=""/>
<feature id="1540" name="liaison" pivot-name="" position=""/>
<feature id="67" name="eupho_quest" pivot-name="eupho_quest" position="0"/>
<feature id="68" name="variation" pivot-name="" position="0"/>
<feature id="69" name="arch" pivot-name="" position="0"/>
<feature id="70" name="possible" pivot-name="" position="0"/>
<feature id="143" name="graphie rectifiée" pivot-name="" position="0"/>
<feature id="199" name="défectif" pivot-name="" position="0"/>
<feature id="200" name="eupho_impératif" pivot-name="" position="0"/>
<feature id="11038" name="forme élidée" pivot-name="elision" position="0"/>
</category>
<category id="12" name="Pronominal" pivot-name="pronominal">
<feature id="246" name="s’" pivot-name="" position="1"/>
<feature id="247" name="se" pivot-name="" position="2"/>
</category>
<category id="13" name="Impersonnel" pivot-name="impersonal">
<feature id="7528" name="il" pivot-name="" position="0"/>
<feature id="7529" name="on" pivot-name="" position="0"/>
<feature id="7530" name="ça" pivot-name="" position="0"/>
</category>
</model>
