<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE model[
<!ELEMENT model (class)>

<!ELEMENT class (class*,instance+)>
<!ATTLIST class
comment CDATA #REQUIRED
id CDATA #REQUIRED
inheritancetype CDATA #REQUIRED
name CDATA #REQUIRED
semfield CDATA #REQUIRED
status CDATA #REQUIRED>

<!ELEMENT instance EMPTY>
<!ATTLIST instance
acttype CDATA #REQUIRED
comment CDATA #IMPLIED
derivation NMTOKEN #REQUIRED
id CDATA #REQUIRED
name CDATA #REQUIRED
status CDATA #REQUIRED>
]>
<model>
<class id="534" name="QQCH." status="1" semfield="0" inheritancetype="0" comment="">
<class id="253" name="ENTITÉ" status="1" semfield="0" inheritancetype="0" comment="">
  <class id="10" name="[UNE]_CRÉATION" status="1" semfield="0" inheritancetype="0" comment="">
    <class id="161" name="COMPOSITION_MUSICALE" status="1" semfield="1" inheritancetype="0" comment="">
      <class id="506" name="PIÈCE_MUSICALE" status="1" semfield="0" inheritancetype="0" comment="">
        <instance id="565" name="pièce musicale" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <instance id="183" name="composition musicale" status="1" derivation="---" acttype="" comment=""/>
      <instance id="829" name="partie de composition musicale" status="1" derivation="PartOf" acttype="" comment=""/>
    </class>
    <class id="191" name="FILM" status="1" semfield="1" inheritancetype="1" comment="">
      <instance id="216" name="film" status="1" derivation="---" acttype="" comment=""/>
      <instance id="833" name="partie de film" status="1" derivation="PartOf" acttype="" comment=""/>
    </class>
    <instance id="10" name="[une] création" status="1" derivation="---" acttype="0" comment=""/>
  </class>
  <class id="25" name="ACCUMULATION_[DE_QQCH.]" status="" semfield="0" inheritancetype="0" comment="">
    <class id="26" name="ACCUMULATION_DE_MATIÈRE_AYANT_UNE_CERTAINE_FORME" status="" semfield="0" inheritancetype="1" comment="">
      <instance id="26" name="accumulation de matière ayant une certaine forme" status="1" derivation="---" acttype="0" comment=""/>
    </class>
    <class id="223" name="DÉPÔT_DE_MATIÈRE" status="1" semfield="0" inheritancetype="1" comment="">
      <instance id="252" name="dépôt de matière" status="1" derivation="---" acttype="" comment=""/>
    </class>
    <instance id="25" name="accumulation [de qqch.]" status="1" derivation="---" acttype="0" comment=""/>
  </class>
  <class id="123" name="BIEN" status="1" semfield="0" inheritancetype="0" comment="">
    <instance id="132" name="bien" status="1" derivation="---" acttype="0" comment=""/>
  </class>
  <class id="242" name="ENSEMBLE_D’ENTITÉS" status="1" semfield="0" inheritancetype="0" comment="">
    <class id="264" name="ESPÈCE_VIVANTE" status="1" semfield="0" inheritancetype="0" comment="">
      <class id="262" name="ESPÈCE_ANIMALE" status="1" semfield="0" inheritancetype="0" comment="L’étiquette ‘espèce animale’ est systématiquement équivalente à
                                                                                                 ‘espèce animale ou animal’ (« un équidé »).">
        <instance id="291" name="espèce animale" status="1" derivation="---" acttype="0" comment=""/>
        <instance id="919" name="qui appartient à une espèce animale" status="1" derivation="A1" acttype="0" comment=""/>
      </class>
      <class id="714" name="ESPÈCE_VÉGÉTALE" status="1" semfield="0" inheritancetype="0" comment="L’étiquette ‘espèce végétale’ est systématiquement équivalente à
                                                                                                  ‘espèce végétale ou végétal’ (« une cucurbitacée »).">
        <instance id="886" name="espèce végétale" status="1" derivation="---" acttype="0" comment=""/>
      </class>
      <instance id="293" name="espèce vivante" status="1" derivation="---" acttype="" comment=""/>
    </class>
    <class id="322" name="GROUPE_HUMAIN" status="1" semfield="0" inheritancetype="0" comment="Cf. « [L’]Homme », « [La] Femme » ; « homo sapiens ».
                                                                                              L’étiquette ‘groupe humain’ est systématiquement équivalente à
                                                                                              ‘groupe humain ou individu’ (« un homo sapiens »).">
      <instance id="368" name="groupe humain" status="1" derivation="---" acttype="" comment=""/>
    </class>
    <instance id="270" name="ensemble d’entités" status="1" derivation="---" acttype="" comment=""/>
  </class>
  <class id="254" name="ENTITÉ_GÉOLOGIQUE" status="1" semfield="0" inheritancetype="0" comment="">
    <instance id="282" name="entité géologique" status="1" derivation="---" acttype="" comment=""/>
  </class>
  <class id="255" name="ENTITÉ_INFORMATIONNELLE" status="1" semfield="0" inheritancetype="0" comment="">
    <class id="730" name="ARGENT" status="1" semfield="0" inheritancetype="0" comment="">
      <class id="577" name="SOMME_D’ARGENT" status="1" semfield="0" inheritancetype="0" comment="">
        <class id="551" name="REVENU" status="1" semfield="0" inheritancetype="0" comment="">
          <instance id="611" name="revenu" status="1" derivation="---" acttype="0" comment=""/>
        </class>
        <instance id="643" name="somme d’argent" status="1" derivation="---" acttype="0" comment=""/>
        <instance id="1026" name="relatif à une somme d’argent" status="1" derivation="A0" acttype="0" comment=""/>
      </class>
    </class>
    <class id="50" name="ACTION_PROGRAMMÉE" status="1" semfield="0" inheritancetype="0" comment="">
      <instance id="56" name="action programmée" status="1" derivation="---" acttype="0" comment=""/>
    </class>
    <class id="715" name="CODE" status="1" semfield="0" inheritancetype="0" comment="">
      <instance id="887" name="code" status="1" derivation="---" acttype="0" comment=""/>
      <instance id="909" name="élément d’un code" status="1" derivation="ElementOf" acttype="0" comment=""/>
    </class>
    <class id="170" name="CONNAISSANCE" status="1" semfield="0" inheritancetype="0" comment="">
      <instance id="192" name="connaissance" status="1" derivation="---" acttype="" comment=""/>
    </class>
    <class id="178" name="CONTENU_INFORMATIONNEL_QU’ON_COMMUNIQUE" status="1" semfield="0" inheritancetype="0" comment="">
      <class id="207" name="DOCUMENT" status="1" semfield="1" inheritancetype="1" comment="">
        <class id="211" name="DOCUMENT_ÉCRIT" status="1" semfield="1" inheritancetype="0" comment="">
          <class id="208" name="DOCUMENT_JUSTIFICATIF" status="1" semfield="0" inheritancetype="0" comment="">
            <instance id="233" name="document justificatif" status="1" derivation="---" acttype="" comment=""/>
          </class>
          <class id="209" name="DOCUMENT_OFFICIEL" status="1" semfield="0" inheritancetype="0" comment="">
            <class id="217" name="DÉCLARATION_OU_DOCUMENT_CORRESPONDANT" status="1" semfield="0" inheritancetype="2" comment="">
              <instance id="245" name="déclaration ou document correspondant" status="1" derivation="---" acttype="" comment=""/>
            </class>
            <class id="32" name="ACTE_OFFICIEL_OU_DOCUMENT_CORRESPONDANT" status="1" semfield="0" inheritancetype="2" comment="">
              <instance id="34" name="acte officiel ou document correspondant" status="1" derivation="---" acttype="0" comment=""/>
            </class>
            <instance id="234" name="document officiel" status="1" derivation="---" acttype="" comment=""/>
          </class>
          <instance id="236" name="document écrit" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <class id="210" name="DOCUMENT_PHOTOGRAPHIQUE" status="1" semfield="1" inheritancetype="0" comment="">
          <instance id="235" name="document photographique" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <instance id="232" name="document" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <class id="634" name="ÉNONCÉ" status="1" semfield="1" inheritancetype="1" comment="">
        <class id="635" name="ÉNONCÉ_EXCLAMATIF" status="1" semfield="0" inheritancetype="0" comment="Distinct de EXCLAMATION, qui est un son produit pour communiquer mais n’est pas un énoncé.">
          <instance id="706" name="le locuteur s’exclame" status="1" derivation="Claus" acttype="" comment=""/>
          <instance id="707" name="énoncé exclamatif" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <class id="541" name="QUESTION" status="1" semfield="0" inheritancetype="0" comment="">
          <instance id="602" name="question" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <class id="636" name="ÉNONCÉ_OU_GESTE_EXPRESSIF" status="1" semfield="0" inheritancetype="1" comment="">
          <instance id="708" name="énoncé ou geste expressif" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <instance id="703" name="le locuteur dit" status="1" derivation="Claus" acttype="" comment=""/>
        <instance id="704" name="relatif à un type d’énoncé" status="1" derivation="A0" acttype="" comment=""/>
        <instance id="705" name="énoncé" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <class id="191" name="FILM" status="1" semfield="1" inheritancetype="1" comment="">
        <instance id="216" name="film" status="1" derivation="---" acttype="" comment=""/>
        <instance id="833" name="partie de film" status="1" derivation="PartOf" acttype="" comment=""/>
      </class>
      <class id="598" name="TEXTE" status="1" semfield="1" inheritancetype="0" comment="">
        <instance id="665" name="texte" status="1" derivation="---" acttype="" comment=""/>
        <instance id="834" name="partie d’un texte" status="1" derivation="PartOf" acttype="" comment=""/>
      </class>
      <instance id="199" name="contenu informationnel qu’on communique" status="1" derivation="---" acttype="" comment=""/>
    </class>
    <class id="329" name="IDÉE" status="1" semfield="0" inheritancetype="0" comment="">
      <instance id="377" name="idée" status="1" derivation="---" acttype="" comment=""/>
    </class>
    <class id="369" name="INFORMATION_[SUR_QQCH.]" status="1" semfield="0" inheritancetype="0" comment="">
      <class id="332" name="INDICATION_[DONNÉE_PAR_QQCH.]" status="1" semfield="0" inheritancetype="0" comment="">
        <class id="420" name="MESURE" status="1" semfield="0" inheritancetype="0" comment="">
          <instance id="472" name="mesure" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <instance id="381" name="[qqch.] indiquer" status="1" derivation="V0" acttype="0" comment=""/>
        <instance id="382" name="indication donnée par qqch." status="1" derivation="---" acttype="" comment=""/>
      </class>
      <class id="370" name="INFORMATION_COMMUNIQUÉE" status="1" semfield="0" inheritancetype="0" comment="INFORMATION_COMMUNIQUÉE renvoie au contenu d’un énoncé et pas à l’énoncé lui-même. Une question est est un énoncé alors qu’une rumeur est une information communiquée -- APol, 16viii2001 (revu, 25i12).">
        <instance id="420" name="information communiquée" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <instance id="419" name="information [sur qqch.]" status="1" derivation="---" acttype="" comment=""/>
    </class>
    <class id="439" name="MÉTHODE" status="1" semfield="0" inheritancetype="0" comment="">
      <class id="440" name="MÉTHODE_DE_SOIN" status="1" semfield="0" inheritancetype="1" comment="">
        <class id="591" name="SUBSTANCE_SERVANT_À_SOIGNER_OU_MÉTHODE_DE_SOIN" status="1" semfield="0" inheritancetype="0" comment="">
          <instance id="658" name="substance servant à soigner ou méthode de soin" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <instance id="497" name="méthode de soin" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <instance id="495" name="méthode" status="1" derivation="---" acttype="" comment=""/>
      <instance id="496" name="relatif à la méthode" status="1" derivation="A0" acttype="" comment="Pour « à la » versus « à une », voir remarque sous ‘relatif au méfait’."/>
    </class>
    <class id="445" name="NOMBRE" status="1" semfield="0" inheritancetype="0" comment="">
      <instance id="503" name="nombre" status="1" derivation="---" acttype="" comment=""/>
    </class>
    <class id="547" name="REPRÉSENTATION" status="1" semfield="0" inheritancetype="0" comment="">
      <class id="331" name="IMAGE" status="1" semfield="1" inheritancetype="0" comment="">
        <instance id="380" name="image" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <instance id="607" name="représentation" status="1" derivation="---" acttype="" comment=""/>
    </class>
    <class id="607" name="UNITÉ_DE_COMPTAGE" status="1" semfield="0" inheritancetype="0" comment="">
      <instance id="676" name="unité de comptage" status="1" derivation="---" acttype="" comment=""/>
    </class>
    <instance id="283" name="entité informationnelle" status="1" derivation="---" acttype="" comment=""/>
  </class>
  <class id="256" name="ENTITÉ_SOCIALE" status="1" semfield="0" inheritancetype="0" comment="">
    <class id="462" name="ORGANISME_SOCIAL" status="1" semfield="0" inheritancetype="0" comment="">
      <class id="63" name="ADMINISTRATION" status="1" semfield="0" inheritancetype="0" comment="">
        <class id="64" name="ADMINISTRATION_OU_CONSTRUCTION_L’ABRITANT" status="1" semfield="0" inheritancetype="1" comment="">
          <instance id="71" name="administration ou construction l’abritant" status="1" derivation="---" acttype="0" comment=""/>
        </class>
        <instance id="70" name="administration" status="1" derivation="---" acttype="0" comment=""/>
      </class>
      <class id="9" name="[UNE]_AUTORITÉ" status="1" semfield="0" inheritancetype="0" comment="">
        <class id="119" name="AUTORITÉ_JUDICIAIRE" status="1" semfield="0" inheritancetype="0" comment="">
          <instance id="128" name="autorité judiciaire" status="1" derivation="---" acttype="0" comment=""/>
        </class>
        <instance id="9" name="[une] autorité" status="1" derivation="---" acttype="0" comment=""/>
      </class>
      <class id="258" name="ENTREPRISE" status="1" semfield="0" inheritancetype="0" comment="">
        <instance id="286" name="entreprise" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <class id="373" name="INSTITUTION" status="1" semfield="0" inheritancetype="0" comment="">
        <class id="374" name="INSTITUTION_OU_CONSTRUCTION_L’ABRITANT" status="1" semfield="0" inheritancetype="1" comment="">
          <instance id="424" name="institution ou construction l’abritant" status="1" derivation="---" acttype="0" comment=""/>
        </class>
        <instance id="423" name="institution" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <class id="638" name="ÉTABLISSEMENT" status="1" semfield="0" inheritancetype="0" comment="">
        <class id="639" name="ÉTABLISSEMENT_COMMERCIAL" status="1" semfield="0" inheritancetype="0" comment="">
          <class id="641" name="ÉTABLISSEMENT_DE_RESTAURATION" status="1" semfield="0" inheritancetype="0" comment="">
            <instance id="713" name="établissement de restauration" status="1" derivation="---" acttype="" comment=""/>
          </class>
          <instance id="711" name="établissement commercial" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <class id="640" name="ÉTABLISSEMENT_CULTUREL" status="1" semfield="0" inheritancetype="0" comment="">
          <class id="643" name="ÉTABLISSEMENT_DE_SPECTACLES" status="1" semfield="0" inheritancetype="0" comment="">
            <instance id="715" name="établissement de spectacles" status="1" derivation="---" acttype="" comment=""/>
          </class>
          <instance id="712" name="établissement culturel" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <class id="642" name="ÉTABLISSEMENT_DE_SOINS" status="1" semfield="0" inheritancetype="0" comment="">
          <instance id="714" name="établissement de soins" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <class id="644" name="ÉTABLISSEMENT_INDUSTRIEL" status="1" semfield="0" inheritancetype="0" comment="">
          <instance id="716" name="établissement industriel" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <instance id="710" name="établissement" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <instance id="521" name="organisme social" status="1" derivation="---" acttype="" comment=""/>
    </class>
    <class id="676" name="[UN]_SERVICE" status="1" semfield="0" inheritancetype="1" comment="">
      <class id="6" name="SERVICE_D’UN_ÉTABLISSEMENT" status="1" semfield="0" inheritancetype="0" comment="">
        <instance id="6" name="service d’un établissement" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <class id="677" name="SERVICE_D’UNE_ADMINISTRATION" status="1" semfield="0" inheritancetype="0" comment="">
        <instance id="767" name="service d’une administration" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <instance id="766" name="[un] service" status="1" derivation="---" acttype="0" comment=""/>
    </class>
    <instance id="284" name="entité sociale" status="1" derivation="---" acttype="" comment=""/>
  </class>
  <class id="257" name="ENTITÉ_VISUELLE" status="1" semfield="0" inheritancetype="0" comment="">
    <class id="306" name="[UNE]_FORME" status="1" semfield="0" inheritancetype="0" comment="Dans le sens de ‘forme géométrique’. Contraste avec ‘forme [de qqch.]’.">
      <class id="298" name="FIGURE" status="1" semfield="0" inheritancetype="0" comment="">
        <instance id="338" name="figure" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <instance id="350" name="[une] forme" status="1" derivation="---" acttype="0" comment=""/>
    </class>
    <class id="632" name="ÉLÉMENT_GRAPHIQUE" status="1" semfield="0" inheritancetype="0" comment="">
      <class id="564" name="SIGNE_GRAPHIQUE" status="1" semfield="0" inheritancetype="0" comment="">
        <class id="565" name="SIGNE_MUSICAL" status="1" semfield="0" inheritancetype="0" comment="">
          <class id="567" name="SILENCE_OU_SIGNE_MUSICAL_LE_REPRÉSENTANT" status="1" semfield="0" inheritancetype="2" comment="">
            <instance id="632" name="silence ou signe musical le représentant" status="1" derivation="---" acttype="" comment=""/>
          </class>
          <instance id="630" name="signe musical" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <instance id="629" name="signe graphique" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <instance id="701" name="élément graphique" status="1" derivation="---" acttype="" comment=""/>
    </class>
    <class id="668" name="ENTITÉ_OU_CARACTÉRISTIQUE_VISUELLE" status="1" semfield="0" inheritancetype="1" comment="">
      <class id="183" name="COULEUR_(DE_QQCH.)" status="1" semfield="1" inheritancetype="0" comment="">
        <instance id="205" name="couleur (de qqch.)" status="1" derivation="---" acttype="" comment=""/>
        <instance id="206" name="d’une certaine couleur" status="1" derivation="A1" acttype="" comment=""/>
      </class>
      <instance id="743" name="entité ou caractéristique visuelle" status="1" derivation="---" acttype="" comment=""/>
    </class>
    <instance id="285" name="entité visuelle" status="1" derivation="---" acttype="" comment=""/>
  </class>
  <class id="395" name="LIEU" status="1" semfield="0" inheritancetype="0" comment="">
    <class id="396" name="LIEU_ABSTRAIT" status="1" semfield="0" inheritancetype="0" comment="">
      <class id="397" name="LIEU_ABSTRAIT_QUI_SÉPARE" status="1" semfield="0" inheritancetype="0" comment="">
        <instance id="448" name="lieu abstrait qui sépare" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <class id="402" name="LIMITE_ABSTRAITE" status="1" semfield="0" inheritancetype="0" comment="">
        <instance id="453" name="limite abstraite" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <class id="710" name="SIÈGE_[DE_QQCH.]" status="1" semfield="0" inheritancetype="0" comment="">
        <instance id="864" name="siège [de qqch.]" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <instance id="447" name="lieu abstrait" status="1" derivation="---" acttype="" comment=""/>
    </class>
    <class id="400" name="LIEU_PHYSIQUE" status="1" semfield="0" inheritancetype="0" comment="">
      <class id="695" name="ENDROIT" status="1" semfield="0" inheritancetype="0" comment="Lieu physique associé à des faits donnés. Par exemple, ARRÊT [d’autobus].">
        <class id="225" name="ENDROIT_AMÉNAGÉ" status="1" semfield="0" inheritancetype="0" comment="Par exemple : AÉROPORT, JARDIN.">
          <instance id="254" name="endroit aménagé" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <class id="226" name="ENDROIT_SYMBOLIQUE" status="1" semfield="0" inheritancetype="0" comment="">
          <instance id="255" name="endroit symbolique" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <class id="696" name="PARTIE_INTÉRIEURE_D’UNE_CONSTRUCTION" status="1" semfield="0" inheritancetype="0" comment="Typiquement, il s’agit d’une partie de construction « où l’on va », qu’on utilise, etc.">
          <instance id="806" name="partie intérieure d’une construction" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <instance id="805" name="endroit" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <class id="613" name="LIEU DE DÉPLACEMENT" status="1" semfield="1" inheritancetype="0" comment="">
        <instance id="682" name="lieu de déplacement" status="1" derivation="---" acttype="" comment=""/>
        <instance id="822" name="partie d’un lieu de déplacement" status="0" derivation="PartOf" acttype="" comment=""/>
      </class>
      <class id="399" name="LIEU_GÉOGRAPHIQUE" status="1" semfield="0" inheritancetype="0" comment="">
        <class id="630" name="ÉLÉMENT_DU_RELIEF" status="1" semfield="1" inheritancetype="0" comment="">
          <class id="186" name="COURS_D’EAU" status="1" semfield="1" inheritancetype="0" comment="">
            <instance id="209" name="cours d’eau" status="1" derivation="---" acttype="" comment=""/>
            <instance id="824" name="partie d’un cours d’eau" status="1" derivation="PartOf" acttype="" comment=""/>
          </class>
          <class id="704" name="ÉTENDUE_D’EAU" status="1" semfield="0" inheritancetype="0" comment="">
            <instance id="842" name="étendue d’eau" status="1" derivation="---" acttype="" comment=""/>
          </class>
          <instance id="699" name="élément du relief" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <class id="654" name="ÉTENDUE_DE_TERRAIN" status="1" semfield="1" inheritancetype="0" comment="">
          <class id="655" name="ÉTENDUE_DE_TERRAIN_BOISÉE" status="1" semfield="0" inheritancetype="0" comment="">
            <instance id="730" name="étendue de terrain boisée" status="1" derivation="---" acttype="" comment=""/>
          </class>
          <class id="656" name="ÉTENDUE_DE_TERRAIN_DESTINÉE_À_UNE_ACTIVITÉ" status="1" semfield="0" inheritancetype="0" comment="">
            <instance id="731" name="étendue de terrain destinée à une activité" status="1" derivation="---" acttype="" comment=""/>
          </class>
          <class id="657" name="ÉTENDUE_DE_TERRAIN_OCCUPÉE" status="1" semfield="0" inheritancetype="0" comment="">
            <instance id="732" name="étendue de terrain occupée" status="1" derivation="---" acttype="" comment=""/>
          </class>
          <instance id="729" name="étendue de terrain" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <class id="718" name="ENTITÉ_GÉOPOLITIQUE" status="1" semfield="0" inheritancetype="0" comment="Voir remarques dans sous-classe PAYS, qui vaut vraisemblablement pour toutes les autres sous-classes.">
          <class id="719" name="PAYS" status="1" semfield="0" inheritancetype="0" comment="Pour la lexie nominale PAYS :
                                                                                           - Structure actancielle : ~ où vivent les X
                                                                                           - Polysémie de base :
                                                                                           a) entité géopolitique
                                                                                           b) population de l’entité géopolitique (« Tout le pays est en émoi. ») => la lexie est sont propre S1
                                                                                           c) entité sociale correspondante (« La France a battu l’Italie 2 à 0. », « Le pays a fermé ses frontières. »)
                                                                                           - Toutes les lexies étiquetées ‘pays’ n’ont pas de copolysèmes correspondants dans le modèle lexical. Ceux-ci sont considérés comme dérivés systématiquement de l’acception unique. Ainsi, tout nom de pays est son propre S1 (acception b) systématiquement dérivable).">
            <instance id="914" name="pays" status="1" derivation="---" acttype="0" comment=""/>
            <instance id="915" name="relatif à un pays" status="1" derivation="A0" acttype="0" comment=""/>
            <instance id="916" name="qqn d’un pays" status="1" derivation="S1" acttype="0" comment=""/>
          </class>
          <instance id="912" name="entité géopolitique" status="1" derivation="---" acttype="0" comment=""/>
          <instance id="913" name="relatif à une entité géopolitique" status="1" derivation="A0" acttype="0" comment=""/>
        </class>
        <instance id="450" name="lieu géographique" status="1" derivation="---" acttype="1" comment=""/>
        <instance id="827" name="partie d’un lieu géographique" status="1" derivation="PartOf" acttype="" comment=""/>
      </class>
      <class id="261" name="ESPACE" status="1" semfield="0" inheritancetype="0" comment="">
        <class id="444" name="NIVEAU_OU_ESPACE_DANS_UNE_CONSTRUCTION" status="1" semfield="0" inheritancetype="0" comment="">
          <class id="645" name="ÉTAGE" status="1" semfield="0" inheritancetype="0" comment="">
            <instance id="717" name="étage" status="1" derivation="---" acttype="" comment=""/>
          </class>
          <instance id="502" name="niveau ou espace dans une construction" status="1" derivation="---" acttype="" comment=""/>
        </class>
        <instance id="290" name="espace" status="1" derivation="---" acttype="" comment=""/>
        <instance id="826" name="partie d’un espace" status="1" derivation="PartOf" acttype="" comment=""/>
      </class>
      <class id="398" name="LIEU_D’HABITATION" status="1" semfield="1" inheritancetype="0" comment="">
        <instance id="449" name="lieu d’habitation" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <class id="401" name="LIEU_QUI_SÉPARE" status="1" semfield="0" inheritancetype="0" comment="">
        <instance id="452" name="lieu qui sépare" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <class id="403" name="LIMITE_PHYSIQUE" status="1" semfield="0" inheritancetype="0" comment="">
        <instance id="454" name="limite physique" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <class id="466" name="PARCOURS" status="1" semfield="0" inheritancetype="0" comment="">
        <instance id="525" name="parcours" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <class id="593" name="SURFACE" status="1" semfield="0" inheritancetype="0" comment="">
        <instance id="660" name="surface" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <instance id="451" name="lieu physique" status="1" derivation="---" acttype="1" comment=""/>
      <instance id="823" name="partie d’un lieu physique" status="1" derivation="PartOf" acttype="" comment=""/>
    </class>
    <instance id="446" name="lieu" status="1" derivation="---" acttype="" comment=""/>
  </class>
  <class id="596" name="TEMPS" status="1" semfield="0" inheritancetype="0" comment="">
    <class id="533" name="PÉRIODE" status="1" semfield="0" inheritancetype="0" comment="">
      <class id="427" name="MOMENT_DE_LA_JOURNÉE" status="1" semfield="0" inheritancetype="0" comment="">
        <class id="545" name="REPAS" status="1" semfield="0" inheritancetype="2" comment="">
          <instance id="605" name="repas" status="1" derivation="---" acttype="" comment=""/>
          <instance id="762" name="faire un repas" status="1" derivation="V0" acttype="" comment=""/>
        </class>
        <instance id="481" name="moment de la journée" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <class id="233" name="ENSEMBLE_DE_FAITS_OU_PÉRIODE_CORRESPONDANTE" status="1" semfield="0" inheritancetype="1" comment="">
        <instance id="262" name="ensemble de faits ou période correspondante" status="1" derivation="---" acttype="" comment=""/>
      </class>
      <instance id="594" name="période" status="1" derivation="---" acttype="0" comment=""/>
      <instance id="941" name="relatif à une certaine période" status="1" derivation="A0" acttype="0" comment=""/>